### ISSUE TITLE
Problems escaping !

### ISSUE THREAD

**Issue by bowmanjd** [comex/rust-shlex#18]
What an excellent crate! I was surprised, though, to see only some problem characters escaped with this snippet:

```rust
fn main() {
    let houdini = "'!!\"*";
    println!("{}", shlex::quote(houdini));
}
```

Which prints the following:
`"'!!\"*"`

The double-bang is, as you might guess, quite problematic in bash and other shells.

The same input is processed by Python, resulting in:
`'\'\'"\'"\'!!"*\''`

This has the advantage of using single quotes (given the `!`).

Am I using `quote()` wrong, though?

**Comment by comex** [comment]
Well, this is a security vulnerability.  Yikes.

**Comment by comex** [comment]
…Looks like it only applies in interactive shells, and only when reading from stdin (i.e. it doesn't happen for a `-c` argument or a shell script argument even if `-i` is set), so thankfully most use cases shouldn't be affected.  Still, it's not impossible for someone to use the crate in a way that could be vulnerable.

**Comment by bowmanjd** [comment]
Yeah, agreed. I would think one would want the asterisk (`*`) escaped too?

**Comment by comex** [comment]
Are there any cases where shells treat `*` specially when inside quotes?  The crate does already treat the presence of `*` as an indication to use quotes.

**Comment by comex** [comment]
After further investigation, this is more complicated than it sounds.  There are two issues.

First, most shells allows `!` to be escaped in double-quotes using a backslash, `\!`, but in `dash` that just gives you the literal text `\!`.  For consistency between shells, we would need to either use `!` within single quotes or `\!` unquoted.

Python's `shlex.quote` only ever uses single quotes, but as a result, single quotes appearing in the input have to be transformed to `'"'"'`.  That's extremely ugly, and it gets worse if something has to be quoted twice for some reason:
```python
>>> print(shlex.quote(shlex.quote("'")))
''"'"''"'"'"'"'"'"'"'"''"'"''
```

That's why I opted for double quotes when I originally wrote this crate.

Second, `!` is only a problem when the shell is reading from user input in interactive mode.  But that is *also* the mode where shells will accept movement shortcuts, e.g. left arrow (`"\x1b[D"`) or Ctrl-A (`"\x01"`).

So just escape control characters too, to be safe, right?  

But it's impossible.  There's no portable shell escape sequence that encodes characters by number.  The `$'...'` syntax can contain hex and octal escapes, but that syntax doesn't work in `dash`, and also isn't understood by `shlex.split` in either Python or this crate.

There is the `printf` utility, which is required by POSIX to understand arbitrary octal escapes.  So technically `\x01` can be 'quoted' into the string `"$(printf '\001')"`, and it will work in any actual POSIX-compatible shell.  But again, it won't work with `shlex.split`.  Nor will it work with the C equivalent, `wordexp`, at least if the flag is passed to disallow command substitution (which modern code will typically pass, for security reasons).

So I think escaping control characters is not an option.  Python does not escape them either.  However, it would be nice to add an alternate escaping mode that isn't POSIX-compatible but in exchange is guaranteed to produce 'well-behaved' text (no control characters, valid UTF-8, maybe other useful properties).

Note that terminals will often prevent you from pasting control characters.  That mitigates the problem from a security perspective; on the other hand, it doesn't help from a functionality perspective, i.e. it doesn't help if you really do want to have a string you can paste in and have the shell expand it to the original binary gunk.  That's where an alternate escaping mode would really shine.

Anyway... the perfect doesn't have to be the enemy of the good, so even if we can't escape control characters, I do think it makes sense to escape `!`.  That implies we need to use single quotes.  Perhaps we should try to be clever:
- If the word contains `!` but not `'`, then use single quotes.
- If the word contains `'` but not `!`, then use double quotes.
- Otherwise, maybe use double quotes and turn `!` into `"\!"` (i.e. close the double quotes, add an unquoted escaped exclamation mark, and re-open the double quotes).  Except be a little smarter to avoid creating empty pairs of double quotes.

I can probably implement this tomorrow.

**Comment by bowmanjd** [comment]
That all sounds brilliant! And, yes, you are right, there is no need to worry about `*` in double quotes or single quotes. I had a mistaken assumption about globbing.

In case it helps, the scenario in which I was attempting to use this crate was in setting passwords to environment variables (there is encryption involved; I am not just using shlex), so I was desiring for shlex.sh.quote to output something like:
`export HARDPASS='P@ssw0rdW1th"!!'` (how I would do it, and how Python shlex.quote does it)
or
`export HARDPASS='P@ssw0rdW1th"'\!''\!''` (how the shell-escape crate does it; unsure why the two empty `''`)
or
`export HARDPASS= "P@ssw0rdW1th\""\!\!`

**Comment by comex** [comment]
FYI, despite it being quite a bit later than tomorrow, I'm still working on this.

**Comment by comex** [comment]
And the reason this took me so long is that addressing it – and adding a fuzzer to test for more bugs like it – led me down a rabbit hole which eventually led to a "real" security vulnerability (one that applies even when you're using the crate in a normal way with noninteractive shells).  [Which is finally published.](https://github.com/comex/rust-shlex/security/advisories/GHSA-r7qv-8r2h-pg27)  And this issue is addressed along with that one.

Handling this took me longer than it should have, but that's sort of what happens when I only have weekends to work on it (and when I didn't spend much time on it over the holiday).  In retrospect, I probably should have published an update as soon as I discovered the `{}` issue, rather than trying to fix everything in one go.
