### ISSUE TITLE
Escape sequence in single quote is wrong?

### ISSUE THREAD

**Issue by sorawee** [comex/rust-shlex#6]
In shell:

```
$ echo '\n'


$ echo '\\n'
\n
```

So obviously shells see `\n` and `\\n` differently. 

However, in your code:

- For `\n`, when `\` is encountered followed by `n`, it pushes both `\` and `n` onto the result.
- For `\\n`, when `\` is encountered followed by `\`, it pushes `\` onto the result. Then, it pushes `n` onto the result. 

So it appears that they are treated in the same way, which as I understand, is incorrect.

**Comment by fenhl** [comment]
This gets somewhat more confusing since `echo` (or at least some implementations of it) looks at the shell lexing output and applies its own rules for escape sequences. Here's a summary of splitting behaviors, tested without relying on `echo` (and let's hope this table doesn't get scrambled by incompatible Markdown implementations — it reads as intended on the GitHub website):

|Implementation|Result for `'\n'`|Result for `'\\n'`|
|---|---|---|
|bash 3.2|`\n`|`\\n`|
|Zsh 5.8|`\n`|`\\n`|
|Python `shlex`|`\n`|`\\n`|
|Rust `shlex`|`\n`|`\n`|

So while none of these result in an actual newline, you're right about the Rust implementation being incorrect, regardless of which implementation is used as a reference point.
